apiVersion: v1
kind: Secret
metadata:
  name: depositlk-secret
type: Opaque
stringData:
  DATABASE_URL: "postgresql://neondb_owner:npg_UdQ7bnAmle0I@ep-shy-waterfall-axwnknnt.c-4.us-east-2.aws.neon.tech/neondb?sslmode=require"